### PR TITLE
Add remove feature

### PR DESCRIPTION
**Pull request by Rebelzob**
# Awesome books project

- Installed linters.
- Added HTML to the project.
- Implemented the add and remove books feature.
- Added Local Storage feature.

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @Rebelzob and @As1imwe-Mark, you are currently missing the webhint  config in your linter setup, please add it 👍🏿

**Comment by Rebelzob** [comment]
> Hi @Rebelzob and @As1imwe-Mark, you are currently missing the Stylelint config in your linter setup, please add it 👍🏿

image

Hi, @prolajumokeoni the linter appears to be added to our project as you can see in the image.

**Comment by prolajumokeoni** [comment]
HI please add the webhint config not stylelint, I updated the comment 👍🏿

**Comment by Rebelzob** [comment]
@prolajumokeoni Linter added successfully, thanks a mil!

**Comment by Asiimwe-Mark** [comment]
I think the linters are added now

**Review by prolajumokeoni — APPROVED** [review]
Hi @Rebelzob and @As1imwe-Mark 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
  - Functions to remove and add book works correctly 👏🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
